### ISSUE TITLE
Question: Advantages over Ernie

### ISSUE THREAD

**Issue by sb8244** [github/ernicorn#3]
Hi Github'ers. There seems to be a lack of knowledge on the interwebs about Ernie, Ernicorn, and why one or the other. I am wondering if you could shed light on it for me.
- Does Github still use Ernie, or is it all Ernicorn now? 
- Does Ernicorn play nicely with Rails? I have Ernie endpoints that have the Rails stack on them right now, but had to fight bugs in Ernie to get it there (utf-8 encoding issues because of ActiveSupport :mask:)
- Any general insight you could provide?

I would greatly appreciate it! I didn't want to tweet at y'all :laughing:

**Comment by rtomayko** [comment]
> Does Github still use Ernie, or is it all Ernicorn now?

No, we haven't used Ernie for some time. It's all Ernicorn now.

> Does Ernicorn play nicely with Rails?

I'm not aware of any issues with Rails specifically. Ernicorn is essentially [Unicorn](http://unicorn.bogomips.org/) repurposed to serve lighter-weight RPC requests instead of HTTP. Unicorn has good support for Rails.

> Any general insight you could provide?

We moved away from Ernie primarily because Erlang introduced a large additional operational and maintenance burden for little gain in this case. We weren't using any of the high concurrency or other unique features of the language in this case so it gave little real benefit over a simple multi-worker Ruby TCP/IP server.
